#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

# Backup the original /etc/hosts file
cp /etc/hosts ~/hosts.new

# Update /etc/hosts with the new IP address mappings
echo "127.0.0.2    localhost" > ~/hosts.new
echo "8.8.8.8      facebook.com" >> ~/hosts.new

# Overwrite the original /etc/hosts file with the updated one
cp -f ~/hosts.new /etc/hosts
