#!/usr/bin/env bash
# Displays all active IPv4 addresses on the machine.

# Use ifconfig to get information about network interfaces
# Filter the output using grep and cut to extract IPv4 addresses
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-

